### ISSUE TITLE
Bug: vehicle-routing-capacity in map path not showing start from depot and ending at depot

### ISSUE THREAD

**Issue by immnas** [TimefoldAI/timefold-quickstarts#106]
**Describe the bug**

vehicle-routing-capacity in map path not showing start from depot and ending at depot

**Expected behavior**

vehicle-routing-capacity in map path should start from depot and ending at depot

**Actual behavior**

is it only the UI bug? at the GET http://localhost:8080/route-plans/{jobid}
I see route plan with customer ID, depot ID, Vehicle iD.

**To Reproduce**
click on "solve"

**Comment by rsynek** [comment]
Thanks for reporting. Indeed it is an issue in the UI and the travel back to the depot is taken into account in the score calculation:
https://github.com/TimefoldAI/timefold-quickstarts/blob/stable/use-cases/vehicle-routing-capacity/src/main/java/org/acme/vehiclerouting/domain/Vehicle.java#L97
