### ISSUE TITLE
Install fails on macOS 14.0 because of Byte Buddy

### ISSUE THREAD

**Issue by jystervinou** [TimefoldAI/timefold-quickstarts#127]
**Describe the bug**
I tried to install the Quickstart examples on macOS 14.0
I got an error about Byte Buddy
**Expected behavior**
Launch the Quickstart correctly

**Actual behavior**
./runQuickstartsFromSource.sh

[WARNING] 
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.3.2:build (default) on project timefold-solver-kotlin-quarkus-school-timetabling-quickstart: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#enhancerDomainObjects threw an exception: org.hibernate.bytecode.enhance.spi.EnhancementException: Failed to enhance class io.quarkus.hibernate.orm.panache.kotlin.PanacheEntity
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:157)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.HibernateEntityEnhancer.enhance(HibernateEntityEnhancer.java:101)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.enhanceEntities(HibernateOrmProcessor.java:1266)
[ERROR] 	at io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor.enhancerDomainObjects(HibernateOrmProcessor.java:627)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.IllegalArgumentException: Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
[ERROR] 	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:96)
[ERROR] 	at net.bytebuddy.pool.TypePool$Default.parse(TypePool.java:855)
[ERROR] 	at net.bytebuddy.pool.TypePool$Default.doDescribe(TypePool.java:841)
[ERROR] 	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.access$001(TypePool.java:921)
[ERROR] 	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution.doResolve(TypePool.java:1019)
[ERROR] 	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1088)
[ERROR] 	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getTypeVariables(TypeDescription.java:8448)
[ERROR] 	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isGenerified(TypeDescription.java:8059)
[ERROR] 	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying.onNonGenericType(TypeDescription.java:1707)
[ERROR] 	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Reifying$1.onNonGenericType(TypeDescription.java:1663)
[ERROR] 	at net.bytebuddy.description.type.TypeDescription$Generic$OfNonGenericType.accept(TypeDescription.java:3672)
[ERROR] 	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:698)
[ERROR] 	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:712)
[ERROR] 	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:637)
[ERROR] 	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:527)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.lambda$resolveGetter$0(ByteBuddyEnhancementContext.java:94)
[ERROR] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.resolveGetter(ByteBuddyEnhancementContext.java:93)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.getGetter(EnhancerImpl.java:545)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.doGetAnnotations(EnhancerImpl.java:574)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.getAnnotations(EnhancerImpl.java:553)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl$AnnotatedFieldDescription.hasAnnotation(EnhancerImpl.java:503)
[ERROR] 	at org.hibernate.bytecode.enhance.spi.DefaultEnhancementContext.isPersistentField(DefaultEnhancementContext.java:103)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.ByteBuddyEnhancementContext.isPersistentField(ByteBuddyEnhancementContext.java:68)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.PersistentAttributeTransformer.collectPersistentFields(PersistentAttributeTransformer.java:123)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.createTransformer(EnhancerImpl.java:384)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.doEnhance(EnhancerImpl.java:371)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.lambda$enhance$0(EnhancerImpl.java:151)
[ERROR] 	at org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.rewrite(ByteBuddyState.java:163)
[ERROR] 	at org.hibernate.bytecode.enhance.internal.bytebuddy.EnhancerImpl.enhance(EnhancerImpl.java:151)
[ERROR] 	... 12 more
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :timefold-solver-kotlin-quarkus-school-timetabling-quickstart

**To Reproduce**
git clone https://github.com/TimefoldAI/timefold-quickstarts.git
cd timefold-quickstarts
./runQuickstartsFromSource.sh

## Environment

**Timefold Solver Version or Git ref**: 

Not sure, last github version :

git clone https://github.com/TimefoldAI/timefold-quickstarts.git

git rev-parse HEAD
a2c43d9c491a3a8ef6144041f73d15e4d39a21c9

**Output of `java -version`:**

openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment Homebrew (build 17.0.8.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8.1+0, mixed mode, sharing)

**Output of `uname -a` or `ver`:**

Darwin 23.0.0 Darwin Kernel Version 23.0.0

## Additional information

Initially i installed Java 21.
I downgraded to Java 17 given the error message about Java 21.
But i still got the same error.

So I provided:

export JAVA_TOOL_OPTIONS="-Dnet.bytebuddy.experimental=true"

then it ran successfully.

./runQuickstartsFromSource.sh                               
Picked up JAVA_TOOL_OPTIONS: -Dnet.bytebuddy.experimental=true
[INFO] Scanning for projects...

**Comment by jystervinou** [comment]
Note : i switched back to Java 21, and it still runs OK with :

export JAVA_TOOL_OPTIONS="-Dnet.bytebuddy.experimental=true"

**Comment by triceo** [comment]
@jystervinou Thanks for reporting!

You are right - this workaround is necessary to run with JDK 21. (Until we upgrade Quarkus to a version that is fully JDK 21 compatible.) In fact, we were using this very workaround in our own code.

However, the part with JDK 17 makes no sense. If I had to guess, the update to JDK 17 didn't go through entirely and the code was still somehow using JDK 21. Anyway...

This problem will be definitely resolved once we release the next version of Timefold Solver, which will bring in the new Quarkus. Stay tuned, should happen later this month.

**Comment by jystervinou** [comment]
That made no sense to me neither, so I made sure to re-clone from git first, verify java -version was indeed v17, but i was still getting the error :-/

**Comment by jystervinou** [comment]
Maybe some PATH was still using 21 or something..

**Comment by triceo** [comment]
Timefold Solver 1.3.0 was released earlier today.
Our CI is entirely green without any 21-specific workarounds.

I think this issue is resolved. Please reopen if you're still having issues.
