### ISSUE TITLE
Broken link in school-timetabling readme

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-quickstarts#138]
1. In https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/use-cases/school-timetabling
2. below the screenshot, click on [Run the application in a container](https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/use-cases/school-timetabling#container)
3. It doesn't scroll down to the anchor

**Comment by ge0ffrey** [comment]
check other quickstart readmes too

**Comment by pieterdeschepper** [comment]
Seems to be fixed. Also checked the other readme's, all looks ok
