### ISSUE TITLE
School timetabling: "by teacher" tab doesn't work on small resolution screen.

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-quickstarts#179]
To reproduce:
- connect to an old beamer with a low resolution screen
- give a live presentation for BeJUG
- run quarkus-school-timetabling, solve the schedule, say "let me show you how that looks for the teachers"
- click on the "by teacher" tab. Nothing happens.
- Panic :)

Please fix for all quickstarts.

**Comment by zepfred** [comment]
It appears that the issue has gone, and it is not possible to reproduce it when utilizing very low resolutions. Closing it.
![resolution1](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/9c3c37cf-a192-4b0d-96b2-13187576baa0)
![resolution2](https://github.com/TimefoldAI/timefold-quickstarts/assets/11961659/58be8deb-0838-44f5-9d9f-09c71d8e008d)
