### ISSUE TITLE
Standardize school-timetabling quickstarts

### ISSUE THREAD

**Issue by triceo** [TimefoldAI/timefold-quickstarts#182]
The [Quarkus school timetabling](https://github.com/TimefoldAI/timefold-quickstarts/blob/stable/use-cases/school-timetabling/README.adoc) quickstart uses a simplified data model, which doesn't use database and doesn't allow to add/remove/edit any items. It also uses a slighty different UI because of that.

The same changes need to be made to the Spring Boot quickstart, and the Kotlin quickstart. The quickstarts should be identical to the Quarkus quickstart, other than the obvious replacing of Quarkus with Spring Boot and Java with Kotlin. (Same UI, same names of field, classes, same data sets etc.)

**Comment by triceo** [comment]
Possibly related to this:
https://github.com/TimefoldAI/timefold-quickstarts/issues/2

**Comment by triceo** [comment]
Also related: https://github.com/TimefoldAI/timefold-solver/issues/98

**Comment by ge0ffrey** [comment]
This will also fix this issue: The technology/java-spring-boot quickstart still shows the CRUD buttons (add lesson etc) but those don't function any more, as we removed the CRUD functionality from the quickstarts to make them more maintainable and easier to understand.
