### ISSUE TITLE
Bug: dependabot is not updating the Gradle depencies

### ISSUE THREAD

**Issue by zepfred** [TimefoldAI/timefold-quickstarts#190]
**Describe the bug**
The Gradle file becomes inconsistent with Maven due to Dependabot upgrading only Maven dependencies.

**Expected behavior**
The modules listed below have dependencies that are expected to be upgraded:
- `Technology/java-spring-boot`
- `hello-world`

**Actual behavior**
Only Maven files are updated.

**Comment by triceo** [comment]
It works!
