### ISSUE TITLE
School timetabling: remove add, edit, delete lesson functionality

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-quickstarts#2]
- [x] quarkus
- [x] spring
- [x] kotlin quarkus

This is preparation to refactor to a simpler more powerful reusable REST api

**Comment by triceo** [comment]
Done.

https://github.com/TimefoldAI/timefold-quickstarts/commit/682cd5d293c32d0681bd50ff105bddc3b5037c0d
https://github.com/TimefoldAI/timefold-quickstarts/commit/790d51ed6d7b0a316c65836d38f34cf9e90358a5
