### ISSUE TITLE
Showcase: build docker image and release it to the Container registry

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-quickstarts#23]
The Timefold Container Registry ( https://github.com/orgs/TimefoldAI/packages ) should contain a docker image with the latest stable showcase so users can easily try it out.

That showcase container image should be able to run all the use-case quickstarts (preferably without having to install their container images).

**Comment by rsynek** [comment]
FYI @ge0ffrey Not yet finished and not yet public, but certainly possible:

https://github.com/TimefoldAI/timefold-quickstarts/pull/24


https://github.com/orgs/TimefoldAI/packages/container/package/timefold-solver-quickstarts-showcase

**Comment by rsynek** [comment]
Ideas to reduce the image size:
A) switch to alpine, explore jLink and sharing dependencies between individual QS
B) native compile all the QS and the showcase; make the showcase support the native QS

B will also make the startups much faster; no more waiting for a QS to become ready.

**Comment by triceo** [comment]
The showcase is gone.
