### ISSUE TITLE
Bug: Enterprise profile doesn't seem to work with Gradle

### ISSUE THREAD

**Issue by triceo** [TimefoldAI/timefold-quickstarts#497]
I tried to run Spring Boot School Timetabling with `-Denterprise`. It never downloaded the enterprise artifacts, which means the profile doesn't work. (But the build succeeded.)

I also tried to specify the property through `gradle.properties`, with the same (no) effect.

**Comment by zepfred** [comment]
@triceo, I cannot reproduce the error. Could you please confirm if the error is still happening?

**Comment by triceo** [comment]
I can no longer reproduce it either. Strange, but so be it.
