### ISSUE TITLE
VRP variants: calculate southWestCorner and northEastCorner on the fly in the UI

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-quickstarts#51]
From a solving point of view, these fields in the solution are obsolete in the VRP variants and the facility location problem:

```
    private Location southWestCorner;
    private Location northEastCorner;
```

The demo-data already contains the depot and all customer locations. From that the southWestCorner and northEastCorner can be calculated as the min(x), min(y), max(x), , max(y) and then adding 5% on every side.

![image](https://github.com/TimefoldAI/timefold-quickstarts/assets/176880/2dd6e89c-f4ab-4b61-a3f6-70252dcd7e75)

**Comment by pieterdeschepper** [comment]
already done
