### ISSUE TITLE
Menu links in readme are missing a section

### ISSUE THREAD

**Issue by ge0ffrey** [TimefoldAI/timefold-quickstarts#562]
In this quickstarts (and potentially others), the readme links is missing a link to the enterprise section

https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/java/employee-scheduling

<img width="296" alt="image" src="https://github.com/user-attachments/assets/cd778f30-6321-4e66-99d6-37d922d50bb4">

**Comment by gocklkatz** [comment]
Hi @ge0ffrey! I added  [PR 575](https://github.com/TimefoldAI/timefold-quickstarts/pull/575) with the necessary changes to resolve this issue.

**Comment by ge0ffrey** [comment]
Thank you @gocklkatz !
Lukas will normally process the PR next week (after PTO).

**Comment by triceo** [comment]
The PR was merged. The change will show up on the stable branch together with the 1.15.0 solver release.
