### ISSUE TITLE
feat: Python /route-plans endpoint should return dynamically generated plan ID instead of static 'ID'

### ISSUE THREAD

**Issue by CatonTheRoRo** [TimefoldAI/timefold-quickstarts#649]
**Describe the bug**
The /route-plans endpoint always returns the string "ID" instead of a unique identifier for the created route plan. This makes it impossible to track or query the created route plan properly.

**Expected behavior**
The endpoint should return a dynamically generated unique identifier for each created route plan, allowing clients to use the ID to track or query the plan.

**Actual behavior**
The endpoint always returns "ID" as a literal string, which is not a valid or useful identifier.

**To Reproduce**

Send a POST request to http://localhost:8080/route-plans with a JSON file, like the example in the demo ui guide:

    curl -X POST -H 'Content-Type:application/json' http://localhost:8080/route-plans -d@sample.json

Observe that the response is "ID".

## Environment

**Timefold Solver Version or Git ref:** Commit e71f1793277391beb91b75515adfc9d6cd9e30f0 (on branch main)

**Output of java -version:**

	openjdk 23 2024-09-17
	OpenJDK Runtime Environment (build 23)
	OpenJDK 64-Bit Server VM (build 23, mixed mode, sharing)

## Additional information

This issue appears to be caused by the solve_route function in the server code, which returns a hardcoded string "ID" instead of generating a unique identifier. The relevant part of the code is:

```python
@app.post("/route-plans")
async def solve_route(route: Annotated[VehicleRoutePlan, Depends(setup_context)]) -> str:
    data_sets['ID'] = route
    solver_manager.solve_and_listen('ID', route,
                                    lambda solution: update_route('ID', solution))
    return 'ID'
```

**Suggested fix:** Replace the hardcoded "ID" with a dynamically generated unique ID.

**Comment by Christopher-Chianelli** [comment]
The Java quickstarts originally also used a static ID to simplify the model (don't need to worry about cleaning up a database/map entries if there is only one problem/solution that can exist).
The Python quickstart was originally developed as a copy of said old model.
However, looking at the current Java quickstart code, they now generate a UUID, so the Python quickstart should change to match.

(that being said, it would have the same issue of eventually running out of memory without cleanup).

**Comment by triceo** [comment]
Thanks for the fix, @Christopher-Chianelli!

That said, @CatonTheRoRo, the quickstarts exist to show you the basics of using the solver, and to get you started quickly. Please keep in mind that it has never been the goal to cover all cases of all possible production use cases - we deliberately ignore a lot of concerns for the sake of brevity and simplicity.
