### ISSUE TITLE
Bug: Duplicate class build error 

### ISSUE THREAD

**Issue by HiddenRoom** [TimefoldAI/timefold-quickstarts#78]
**Describe the bug**
I executed runQuickStartsFromSource.sh and it downloaded thing fine but when the build started it failed with a class duplication error and this message (this is the error message after re-running once so the downloads don't take up too much space): 

[INFO] --- quarkus:3.2.0.Final:dev (default-cli) @ timefold-solver-quickstarts-showcase ---
[INFO] Invoking org.apache.maven.plugins:maven-enforcer-plugin:3.3.0:enforce (enforce-no-logback-test-in-main) @ timefold-solver-quickstarts-showcase
[INFO] Rule 0: org.apache.maven.enforcer.rules.files.RequireFilesDontExist passed
[INFO] Rule 1: org.commonjava.maven.enforcer.rule.EnforceManagedDepsRule(requireManagedDeps) passed
[INFO] Rule 2: org.apache.maven.enforcer.rules.dependency.BannedDependencies passed
[INFO] Adding ignore: module-info
[INFO] Adding ignore: META-INF/versions/*/module-info
[INFO] Adding ignore: module-info
[INFO] Adding ignore: META-INF/versions/*
[INFO] Adding ignorable dependency: io.quarkus:quarkus-ide-launcher:null
[INFO]   Adding ignore: *
[INFO] Rule 4: org.apache.maven.enforcer.rules.BanDuplicatePomDependencyVersions passed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.321 s
[INFO] Finished at: 2023-07-06T23:07:33-07:00
[INFO] ------------------------------------------------------------------------
[WARNING] 
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-site-plugin:3.12.1
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.2.0.Final:dev (default-cli) on project timefold-solver-quickstarts-showcase: 
[ERROR] Rule 3: org.codehaus.mojo.extraenforcer.dependencies.BanDuplicateClasses failed with message:
[ERROR] Duplicate classes found:
[ERROR] 
[ERROR]   Found in:
[ERROR]     org.codehaus.plexus:plexus-xml:jar:4.0.0:test
[ERROR]     org.codehaus.plexus:plexus-utils:jar:3.5.1:test
[ERROR]   Duplicate classes:
[ERROR]     org/codehaus/plexus/util/xml/pull/EntityReplacementMap.class
[ERROR]     org/codehaus/plexus/util/xml/XmlReaderException.class
[ERROR]     org/codehaus/plexus/util/xml/XmlStreamReaderException.class
[ERROR]     org/codehaus/plexus/util/xml/XmlStreamReader.class
[ERROR]     org/codehaus/plexus/util/xml/pull/MXParser.class
[ERROR]     org/codehaus/plexus/util/xml/CompactXMLWriter.class
[ERROR]     org/codehaus/plexus/util/xml/Xpp3DomUtils.class
[ERROR]     org/codehaus/plexus/util/xml/pull/MXSerializer.class
[ERROR]     org/codehaus/plexus/util/xml/pull/XmlSerializer.class
[ERROR]     org/codehaus/plexus/util/xml/PrettyPrintXMLWriter.class
[ERROR]     org/codehaus/plexus/util/xml/pull/XmlPullParser.class
[ERROR]     org/codehaus/plexus/util/xml/SerializerXMLWriter.class
[ERROR]     org/codehaus/plexus/util/xml/XmlWriterUtil.class
[ERROR]     org/codehaus/plexus/util/xml/pull/XmlPullParserException.class
[ERROR]     org/codehaus/plexus/util/xml/XMLWriter.class
[ERROR]     org/codehaus/plexus/util/xml/XmlReader.class
[ERROR]     org/codehaus/plexus/util/xml/XmlStreamWriter.class
[ERROR]     org/codehaus/plexus/util/xml/Xpp3DomWriter.class
[ERROR]     org/codehaus/plexus/util/xml/XmlUtil.class
[ERROR] 
[ERROR]   Found in:
[ERROR]     org.codehaus.plexus:plexus-xml:jar:4.0.0:test
[ERROR]     org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:test
[ERROR]     org.codehaus.plexus:plexus-utils:jar:3.5.1:test
[ERROR]   Duplicate classes:
[ERROR]     org/codehaus/plexus/util/xml/Xpp3DomBuilder.class
[ERROR]     org/codehaus/plexus/util/xml/Xpp3Dom.class
[ERROR]     org/codehaus/plexus/util/xml/Xpp3DomBuilder$InputLocationBuilder.class
[ERROR] 
[ERROR]   Found in:
[ERROR]     org.codehaus.plexus:plexus-xml:jar:4.0.0:test
[ERROR]     org.apache.maven:maven-xml-impl:jar:4.0.0-alpha-5:test
[ERROR]   Duplicate classes:
[ERROR]     org/codehaus/plexus/util/xml/Xpp3Dom$ChildrenTracking.class
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Expected behavior**
Proper build

**Actual behavior**
Build failed

**To Reproduce**
clone repo and execute runQuickStartsFromSource.sh

## Environment

git repo cloned on 05/07/23 at 23:45 (MST)

openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)

Linux profile-name 6.4.1-artix1-1 #1 SMP PREEMPT_DYNAMIC Sat, 01 Jul 2023 18:50:59 +0000 x86_64 GNU/Linux

**Comment by triceo** [comment]
Thanks for reporting! 
I will look into this.

**Comment by triceo** [comment]
The following PR will fix it for the `development` branch:
https://github.com/TimefoldAI/timefold-solver/pull/167

We're not yet sure if we're going to do a `1.0.1` release for this to fix the `stable` branch as well. Worst case, it will be fixed with _Timefold Solver 1.1.0_. 

In the meantime, the `development` branch will work, and the individual quickstarts work even now. (Outside of the showcase.)

**Comment by ge0ffrey** [comment]
We ran into this today. It breaks the getting started experience.
Let's do a 1.0.1 release.

**Comment by ge0ffrey** [comment]
Alternative solution: add an enforcer skip in a commit to timefold-quickstarts's root pom.xml on the stable branch only.

**Comment by triceo** [comment]
When the referenced PR is merged, the Maven build of the showcase will work again.
