### ISSUE TITLE
Where is https://timefold.ai/model/job-shop-scheduling/

### ISSUE THREAD

**Issue by Galileon-venta** [TimefoldAI/timefold-quickstarts#97]
Run Model from the Planning Models leads to https://github.com/TimefoldAI/timefold-quickstarts/tree/stable/use-cases/food-packaging not JSSP/Job Shop Scheduling Problem

Where to find the example?

**Comment by ge0ffrey** [comment]
Food packaging is a variation on job shop scheduling  . We currently don't have a dedicated quickstart.

**Comment by triceo** [comment]
I'm closing this issue, as we have an answer.

Feel free to continuing the conversation by [asking a question](https://stackoverflow.com/questions/ask?tags=timefold) or [starting a discussion](https://github.com/TimefoldAI/timefold-solver/discussions/new?category=general).
